defaults:
  - model: dinov2
  - dataset: first_week_dataset
  - optim: adamw
  - loss_fn: cross_entropy

epochs: 20

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  real_images_val_path: ${dataset.real_images_val_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}
  mixup_dir: ${dataset.mixup}

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/ckpt/${experiment_name}

experiment_name: DINOv2_g_
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true